### PR TITLE
vis-weather added

### PR DESCRIPTION
**Pull request by rg-engineering**
I just added vis-weather... I tested it here and it works well on my machine...

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Thank you four your PR. 
I need Licence Agreement from you. 
Is it ok for you if I will just make the change myself? 
Or do you want to sign the LA?

Best regards Bluefox.

**Comment by GermanBluefox** [comment]
Thank you four your PR. 
I need Licence Agreement from you. 
Is it ok for you if I will just make the change myself? 
Or do you want to sign the LA?

Best regards Bluefox.

**Comment by rg-engineering** [comment]
Please do the necessary changes by yourself. That's fine for me.

rgds.
René

**Comment by GermanBluefox** [comment]
Manually added. Thank you

**Pull request closed without merging**
